security:
  oauth2:
    resource:
      userInfoUri: http://localhost:8901/auth/user

#Setting the logging levels for the service
logging:
  level:
#    root: DEBUG
    com.netflix: WARN
    org.springframework.web: WARN
    com.coopersoft: DEBUG


eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
        defaultZone: http://discovery:8761/eureka/