security:
  oauth2:
    resource:
      userInfoUri: http://localhost:8901/auth/user

#Setting the logging levels for the service
logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    cc.coopersoft: DEBUG


eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
        defaultZone: http://localhost:8761/eureka/




spring:
  cloud:
    config:
      uri: http://localhost:8888
  profiles:
    active: "default"
  jpa:
    database: "MYSQL"
    show-sql: "true"
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.MySQL5Dialect"
    hibernate:
      naming:
        physical-strategy: "org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl"
  datasource:
    test-while-idle: "true"
    validationQuery: "SELECT 1"
    url: "jdbc:mysql://localhost:3306/archives?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false"
    username: "root"
    password: "p0stgr@s"
    driver-class-name: "com.mysql.cj.jdbc.Driver"

signing:
  key: "345345fsdfsf5345"